//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> ClinicId { get; set; }
        public string ReceiptionistId { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
